apiVersion: v1
kind: Service
metadata:
  name: rancher-lb
spec:
  ports:
  - port: 80
    nodePort: 31001
    targetPort: http-port
    protocol: TCP
  selector:
    app: rancher
  type: LoadBalancer
