apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld.example.com
  labels:
    app: helloworld
spec:
  containers:
  - name: k8s
    image: harbor.corp.local/library/project1:v1
    ports:
    - name: nodejs-port
      containerPort: 3000
