kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-storage
  annotations:
    volume.beta.kubernetes.io/storage-class: demo-sc-vsan
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
