kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: web-storage
  annotations:
    volume.beta.kubernetes.io/storage-class: thin-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

