apiVersion: v1
kind: ReplicationController
metadata:
  name: helloworld-controller
spec:
  replicas: 4
  selector:
    app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld-v2
        image: yaviram/myrepo:v2
        ports:
        - name: nodejs-port
          containerPort: 3000
